// Route list
export const ROUTE_LIST = [
	{ name: 'Login', path: '/login', component: () => import('@/pages/auth/Login.vue'), meta: { title: 'Login', layout: 'auth' }, },
	{ name: 'Logout', path: '/logout', component: () => import('@/pages/auth/Logout.vue'), meta: { title: 'Logout', layout: 'auth' }, },
	{ name: 'ForgotPassword', path: '/forgot-password', component: () => import('@/pages/auth/ForgotPassword.vue'), meta: { title: 'Forgot Password', layout: 'auth' }, },
	{ name: 'ResetPassword', path: '/password/reset', component: () => import('@/pages/auth/ResetPassword.vue'), meta: { title: 'Reset Password', layout: 'auth' }, },
	{ name: 'Register', path: '/register', component: () => import('@/pages/auth/Register.vue'), meta: { title: 'Register', layout: 'auth' }, },
	{ name: 'Resend Email', path: '/resend-email', component: () => import('@/pages/auth/ResendEmail.vue'), meta: { title: 'Resend Email', layout: 'auth' }, },
	{ name: 'Verify', path: '/user/verify', component: () => import('@/pages/auth/Verify.vue'), meta: { title: 'Verify', layout: 'auth' }, },
	{ name: 'Index', path: '/', component: () => import('@/pages/home/Index.vue'), meta: { title: 'Home', layout: 'main' }, },
	{ name: 'Reports', path: '/reports', component: () => import('@/pages/report/Index.vue'), meta: { title: 'Reports', layout: 'main' }, },
	{ name: 'Users', path: '/users', component: () => import('@/pages/users/Index.vue'), meta: { title: 'Users', layout: 'main' }, },
	{ name: 'Teams', path: '/teams', component: () => import('@/pages/teams/Index.vue'), meta: { title: 'Teams', layout: 'main' }, },
	{ name: 'Events', path: '/events', component: () => import('@/pages/events/Index.vue'), meta: { title: 'Events', layout: 'main' }, },
	{ name: 'EventDetails', path: '/events/:slug', component: () => import('@/pages/events/Details.vue'), meta: { title: 'Event Details', layout: 'main' }, },
	{ name: 'Templates', path: '/templates', component: () => import('@/pages/templates/Index.vue'), meta: { title: 'Templates', layout: 'main' }, },
	{ name: 'TemplateDetails', path: '/templates/:slug', component: () => import('@/pages/templates/Details.vue'), meta: { title: 'Templates Details', layout: 'main' }, },
	{ name: 'Categories', path: '/categories', component: () => import('@/pages/categories/Index.vue'), meta: { title: 'Categories', layout: 'main' }, },
	{ name: 'Announcements', path: '/announcements', component: () => import('@/pages/announcements/Index.vue'), meta: { title: 'Announcements', layout: 'main' }, },
	{ name: 'Changelogs', path: '/changelogs', component: () => import('@/pages/changelogs/Index.vue'), meta: { title: 'Changelogs', layout: 'main' }, },
	{ name: 'Feedbacks', path: '/feedbacks', component: () => import('@/pages/feedbacks/Index.vue'), meta: { title: 'Feedbacks', layout: 'main' }, },
	{ name: 'Tags', path: '/tags', component: () => import('@/pages/tags/Index.vue'), meta: { title: 'Tags', layout: 'main' }, },
	{ name: 'Settings', path: '/settings', component: () => import('@/pages/settings/Index.vue'), meta: { title: 'Settings', layout: 'main' }, },
	{ name: 'Profile', path: '/profile', component: () => import('@/pages/profile/Index.vue'), meta: { title: 'Profile', layout: 'main' }, },
	{ name: 'Groups', path: '/groups', component: () => import('@/pages/groups/Index.vue'), meta: { title: 'Groups', layout: 'main' }, },
	{ name: 'Contacts', path: '/contacts', component: () => import('@/pages/contacts/Index.vue'), meta: { title: 'Contacts', layout: 'main' }, },
	{ name: 'NotFound', path: '/:path(.*)', component: () => import('@/pages/errors/NotFound.vue'), meta: { title: 'Not Found', layout: 'main' }, },
];