export const EVENT_DEFAULT = {
	id: null,
	name: '',
	description: '',
	type: 'public',
	information: '',
	dress_code: '',
	performance: '',
	latitude: '',
	longitude: '',
	company: '',
	status: '',
	start_time: '',
	end_time: '',
	location: '',
	tags: null,
	icon: null,
	max_total_participant: 0,
	is_paid: false,
	is_published: false,
	settings: {},
	custom_attendees: [],
};


export const EVENT_TYPES = [
	{ id: 'wedding', name: 'Wedding' },
	{ id: 'exhibition', name: 'Exhibitions' },
	{ id: 'seminar', name: 'Seminars' },
	{ id: 'conference', name: 'Conferences' },
	{ id: 'reunion', name: 'Reunions' },
	{ id: 'themed_party', name: 'Themed Parties' },
	{ id: 'webinar', name: 'Webinars' },
	{ id: 'classes', name: 'Classes' },
	{ id: 'auction', name: 'Auctions' },
	{ id: 'sales', name: 'Sales' },
	{ id: 'dinner', name: 'Dinners' },
	{ id: 'music_festival', name: 'Music Festivals' },
	{ id: 'food_festival', name: 'Food Festivals' },
	{ id: 'boutique_shop', name: 'Boutique shops' },
]