export const EVENT_DEFAULT = {
	id: null,
	name: '',
	description: '',
	type: 'public',
	information: '',
	dress_code: '',
	performance: '',
	latitude: '',
	longitude: '',
	company: '',
	status: '',
	start_time: '',
	end_time: '',
	location: '',
	tags: null,
	icon: null,
	max_total_participant: 0,
	is_paid: false,
	is_published: false,
	settings: {},
	custom_attendees: [],
};