export const EVENT_DEFAULT = {
	id: null,
	name: '',
	description: '',
	type: 'public',
	information: '',
	dress_code: '',
	performance: '',
	latitude: 0,
	longitude: 0,
	company: '',
	status: '',
	start_time: '',
	end_time: '',
	location: '',
	tags: null,
	icon: null,
	max_total_participant: 0,
	is_paid: false,
	is_published: false,
	settings: {},
	custom_attendees: [],
};

export const EVENT_TYPES = [
	{ id: 'wedding', name: 'Wedding', is_available: true },
	{ id: 'birthday', name: 'Birthday', is_available: true },
	{ id: 'exhibition', name: 'Exhibitions', is_available: true },
	{ id: 'seminar', name: 'Seminars', is_available: false },
	{ id: 'conference', name: 'Conferences', is_available: false },
	{ id: 'reunion', name: 'Reunions', is_available: false },
	{ id: 'themed_party', name: 'Themed Parties', is_available: false },
	{ id: 'webinar', name: 'Webinars', is_available: false },
	{ id: 'classes', name: 'Classes', is_available: false },
	{ id: 'auction', name: 'Auctions', is_available: false },
	{ id: 'sales', name: 'Sales', is_available: false },
	{ id: 'dinner', name: 'Dinners', is_available: false },
	{ id: 'music_festival', name: 'Music Festivals', is_available: false },
	{ id: 'food_festival', name: 'Food Festivals', is_available: false },
	{ id: 'boutique_shop', name: 'Boutique shops', is_available: false },
]